version: '3'
services:
  text-selection:
    container_name: text-selection
    restart: always
    build: text_selection/
    ports:
     - "5001:5000"

  character-recognition:
    container_name: character-recognition
    restart: always
    build: character_recognition/
    ports:
     - "5002:5000"

  client:
    container_name: client
    restart: always
    build: client/
    env_file:
      - client/.env
    ports:
     - "5003:5000"

  postgres:
      container_name: postgres
      restart: always
      build: postgres/
      env_file: postgres/.env
      ports:
        - "5003:5432"