version: '3'
services:
  text-selection:
    container_name: text-selection
    restart: always
    build: text_selection/
    ports:
     - "5001:5000"

  character-recognition:
    container_name: character-recognition
    restart: always
    build: character_recognition/
    ports:
     - "5002:5000"